/**
* Site Configuration
* Generated by Netlify Function
* Last updated: 2026-01-27T18:01:59.109Z
*/

// contactInfo configuration
export const contactInfo = {
    agent: {
      name: "Matt Goch",
      photo: "https://cdn.prod.website-files.com/665d1d5be18f39e01a4f2038/665d41576fbab8792a5daae1_Web-33.jpg",
      phone: "905-401-0610",
      email: "matt@gochrealestate.com",
      company: "Exp Realty",
      companyLogo: "https://cdn.prod.website-files.com/665d1d5be18f39e01a4f2038/6767bb0206432a900589eb6b_MG%20Horizontal%20Logo%20-%20PRINT%20VERSIONS%20(2500%20x%201000%20px)%20(1)-p-500.png",
      companyAddress: "4025 DORCHESTER ROAD, SUITE 260 NIAGARA FALLS, Ontario L2E7K8",
      license: "REALTOR®",
      repo: "New-Listing-24"
    },
    social: {
      instagram: "https://www.instagram.com/mattgoch.realtor/",
      facebook: "https://www.facebook.com/mattgoch.realtor",
      linkedin: ""
    },
    email: "matt@gochrealestate.com",
    phone: "905-401-0610",
    address: "3446 Black Creek Rd",
    socialLinks: {
      instagram: "https://www.instagram.com/mattgoch.realtor/",
      facebook: "https://www.facebook.com/mattgoch.realtor",
      linkedin: ""
    },
    agent2: null
  };

// formAutomations configuration
export const formAutomations = {
    crmLeadParsingEmail: "",
    sgApiKey: ""
  };

// formQuestions configuration
export const formQuestions = [
    {
      id: 1,
      key: "currentSituation",
      question: "What is your current situation?",
      order: 1,
      options: [
        {
          value: "own",
          label: "I own my home",
          emoji: "🏠"
        },
        {
          value: "rent",
          label: "I rent",
          emoji: "🔑"
        },
        {
          value: "family",
          label: "Live with family/friends",
          emoji: "👨‍👩‍👧"
        },
        {
          value: "between",
          label: "Between homes",
          emoji: "📦"
        }
      ]
    },
    {
      id: 2,
      key: "lookingToDo",
      question: "What are you looking to do?",
      order: 2,
      options: [
        {
          value: "buy",
          label: "Buy a home",
          emoji: "🏡"
        },
        {
          value: "sell-buy",
          label: "Sell and buy",
          emoji: "🔄"
        },
        {
          value: "rent",
          label: "Rent a place",
          emoji: "🗝️"
        },
        {
          value: "invest",
          label: "Invest in property",
          emoji: "💰"
        }
      ]
    },
    {
      id: 3,
      key: "movingTimeline",
      question: "When are you planning to move?",
      order: 3,
      options: [
        {
          value: "asap",
          label: "ASAP",
          emoji: "🚀"
        },
        {
          value: "3-6months",
          label: "3-6 months",
          emoji: "📅"
        },
        {
          value: "6-12months",
          label: "6-12 months",
          emoji: "⏰"
        },
        {
          value: "12+months",
          label: "12+ months",
          emoji: "🔮"
        }
      ]
    }
  ];

// galleryImages configuration
export const galleryImages = [
    {
      id: 1,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1769200309659-MLS-2.jpg",
      alt: "Property image 1",
      category: ""
    },
    {
      id: 2,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1769200311061-MLS-3.jpg",
      alt: "Property image 2",
      category: ""
    },
    {
      id: 3,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1769200311867-MLS-4.jpg",
      alt: "Property image 3",
      category: ""
    },
    {
      id: 4,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1769200312380-MLS-5.jpg",
      alt: "Property image 4",
      category: ""
    },
    {
      id: 5,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1769200312721-MLS-6.jpg",
      alt: "Property image 5",
      category: ""
    },
    {
      id: 6,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1769200313214-MLS-7.jpg",
      alt: "Property image 6",
      category: ""
    },
    {
      id: 7,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1769200313571-MLS-8.jpg",
      alt: "Property image 7",
      category: ""
    },
    {
      id: 8,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1769200313798-MLS-9.jpg",
      alt: "Property image 8",
      category: ""
    },
    {
      id: 9,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1769200314209-MLS-10.jpg",
      alt: "Property image 9",
      category: ""
    },
    {
      id: 10,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1769200314504-MLS-11.jpg",
      alt: "Property image 10",
      category: ""
    },
    {
      id: 11,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1769200314783-MLS-12.jpg",
      alt: "Property image 11",
      category: ""
    },
    {
      id: 12,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1769200315139-MLS-13.jpg",
      alt: "Property image 12",
      category: ""
    },
    {
      id: 13,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1769200315393-MLS-14.jpg",
      alt: "Property image 13",
      category: ""
    },
    {
      id: 14,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1769200315686-MLS-15.jpg",
      alt: "Property image 14",
      category: ""
    },
    {
      id: 15,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1769200315887-MLS-16.jpg",
      alt: "Property image 15",
      category: ""
    },
    {
      id: 16,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1769200316195-MLS-17.jpg",
      alt: "Property image 16",
      category: ""
    },
    {
      id: 17,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1769200316521-MLS-18.jpg",
      alt: "Property image 17",
      category: ""
    },
    {
      id: 18,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1769200316909-MLS-19.jpg",
      alt: "Property image 18",
      category: ""
    },
    {
      id: 19,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1769200317334-MLS-20.jpg",
      alt: "Property image 19",
      category: ""
    },
    {
      id: 20,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1769200317597-MLS-21.jpg",
      alt: "Property image 20",
      category: ""
    },
    {
      id: 21,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1769200317905-MLS-22.jpg",
      alt: "Property image 21",
      category: ""
    },
    {
      id: 22,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1769200318292-MLS-23.jpg",
      alt: "Property image 22",
      category: ""
    },
    {
      id: 23,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1769200318511-MLS-24.jpg",
      alt: "Property image 23",
      category: ""
    },
    {
      id: 24,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1769200319429-MLS-25.jpg",
      alt: "Property image 24",
      category: ""
    },
    {
      id: 25,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1769200320024-MLS-26.jpg",
      alt: "Property image 25",
      category: ""
    },
    {
      id: 26,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1769200320273-MLS-27.jpg",
      alt: "Property image 26",
      category: ""
    },
    {
      id: 27,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1769200320534-MLS-28.jpg",
      alt: "Property image 27",
      category: ""
    },
    {
      id: 28,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1769200321569-MLS-29.jpg",
      alt: "Property image 28",
      category: ""
    },
    {
      id: 29,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1769200325912-MLS-30.jpg",
      alt: "Property image 29",
      category: ""
    },
    {
      id: 30,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1769200330867-MLS-31.jpg",
      alt: "Property image 30",
      category: ""
    },
    {
      id: 31,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1769200334300-MLS-32.jpg",
      alt: "Property image 31",
      category: ""
    },
    {
      id: 32,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1769200336293-MLS-33.jpg",
      alt: "Property image 32",
      category: ""
    },
    {
      id: 33,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1769200339822-MLS-34.jpg",
      alt: "Property image 33",
      category: ""
    },
    {
      id: 34,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1769200342501-MLS-35.jpg",
      alt: "Property image 34",
      category: ""
    },
    {
      id: 35,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1769200344514-MLS-36.jpg",
      alt: "Property image 35",
      category: ""
    },
    {
      id: 36,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1769200345408-MLS-37.jpg",
      alt: "Property image 36",
      category: ""
    },
    {
      id: 37,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1769200346645-MLS-38.jpg",
      alt: "Property image 37",
      category: ""
    },
    {
      id: 38,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1769200349350-MLS-39.jpg",
      alt: "Property image 38",
      category: ""
    },
    {
      id: 39,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1769200350556-MLS-40.jpg",
      alt: "Property image 39",
      category: ""
    },
    {
      id: 40,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1769200351017-MLS-41.jpg",
      alt: "Property image 40",
      category: ""
    },
    {
      id: 41,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1769200351693-MLS-42.jpg",
      alt: "Property image 41",
      category: ""
    },
    {
      id: 42,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1769200352202-MLS-43.jpg",
      alt: "Property image 42",
      category: ""
    },
    {
      id: 43,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1769200352597-MLS-44.jpg",
      alt: "Property image 43",
      category: ""
    },
    {
      id: 44,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1769200353029-MLS-45.jpg",
      alt: "Property image 44",
      category: ""
    },
    {
      id: 45,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1769200354039-MLS.jpg",
      alt: "Property image 45",
      category: ""
    }
  ];

// homeShowcaseSections configuration
export const homeShowcaseSections = [
    {
      id: "section1",
      title: "4 Bedrooms",
      description: "Kitchen, people love the size of it, space in the kitchen, big island in the middle  ",
      image: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1769200309659-MLS-2.jpg"
    },
    {
      id: "section2",
      title: "2 Bathrooms",
      description: "",
      image: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1769200311061-MLS-3.jpg"
    },
    {
      id: "section3",
      title: "2,278 sq ft",
      description: "Spacious living area with ample room for your lifestyle",
      image: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1769200311867-MLS-4.jpg"
    },
    {
      id: "section4",
      title: "$649,900",
      description: "",
      image: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1769200312380-MLS-5.jpg"
    }
  ];

// neighborhood configuration
export const neighborhood = {
    name: "Black Creek",
    city: "Fort Erie",
    description: "Black Creek is a riverside neighbourhood in Fort Erie with close access to regional parks and historic sites along the Niagara corridor. The area is oriented toward driving and outdoor recreation — residents enjoy proximity to waterfront trails, family attractions and seasonal events.",
    highlights: [
      "Old Fort Erie – War of 1812 historic site with reenactments and demonstrations",
      "Safari Niagara – regional wildlife attraction and family destination",
      "Fort Erie Race Track – seasonal live thoroughbred racing and dining venues",
      "Friendship Trail – scenic multi-kilometre path for walking and cycling along the waterfront",
      "Fort Erie Historical Museum – local history exhibits in a restored 19th‑century building"
    ]
  };

// neighborhoodAmenities configuration
export const neighborhoodAmenities = [
    {
      id: 1,
      name: "Clifton Hill",
      distance: "Nearby — see map",
      category: "shopping",
      icon: "ShoppingBag"
    },
    {
      id: 2,
      name: "Black Creek Riverside Park",
      distance: "Nearby — see map",
      category: "recreation",
      icon: "Leaf"
    },
    {
      id: 3,
      name: "Fort Erie Historical Museum",
      distance: "Nearby — see map",
      category: "education",
      icon: "School"
    },
    {
      id: 4,
      name: "Waffle Bandits",
      distance: "Nearby — see map",
      category: "dining",
      icon: "Coffee"
    },
    {
      id: 5,
      name: "Maggie's Grill",
      distance: "Nearby — see map",
      category: "dining",
      icon: "Utensils"
    },
    {
      id: 6,
      name: "Niagara Transit / Go Transit Bus Garage",
      distance: "Nearby — see map",
      category: "transportation",
      icon: "Car"
    },
    {
      id: 7,
      name: "Niawanda Park",
      distance: "Nearby — see map",
      category: "recreation",
      icon: "Users"
    },
    {
      id: 8,
      name: "Niagara Falls Transit Terminal",
      distance: "Nearby — see map",
      category: "business",
      icon: "Wifi"
    }
  ];

// neighborhoodStats configuration
export const neighborhoodStats = [
    {
      id: 1,
      title: "Walk Score",
      value: "10/100",
      caption: "Car-Dependent",
      icon: "BadgeCheck",
      color: "bg-green-500"
    },
    {
      id: 2,
      title: "Transit Score",
      value: "N/A",
      caption: "Limited Transit",
      icon: "Compass",
      color: "bg-blue-500"
    },
    {
      id: 3,
      title: "Bike Score",
      value: "27/100",
      caption: "Somewhat Bikeable",
      icon: "Compass",
      color: "bg-blue-500"
    }
  ];

// openHouseDetails configuration
export const openHouseDetails = {
    date: "",
    startTime: "",
    endTime: "",
    registerLink: "",
    host: "",
    phone: "",
    email: "",
    ctaText: ""
  };

// packageItems configuration
export const packageItems = [
    {
      id: 1,
      title: "Detailed Floor Plans",
      description: "Complete architectural layouts showing the 4 bedroom, 2 bathroom configuration with precise measurements.",
      icon: "FileText"
    },
    {
      id: 2,
      title: "Recent Neighborhood Sales",
      description: "Comparative market analysis of recent Detached sales in Fort Erie.",
      icon: "BarChart2"
    },
    {
      id: 3,
      title: "School District Information",
      description: "District School Board of Niagara ",
      icon: "GraduationCap"
    },
    {
      id: 4,
      title: "Property Inspection Report",
      description: "Professional assessment highlighting recent upgrades and maintenance history.",
      icon: "CheckSquare"
    },
    {
      id: 5,
      title: "Financing Options Guide",
      description: "Current mortgage rates and financing programs available for this price range.",
      icon: "DollarSign"
    },
    {
      id: 6,
      title: "Neighborhood Amenities Map",
      description: "Interactive guide to nearby amenities and transportation options.",
      icon: "Map"
    }
  ];

// property configuration
export const property = {
    name: "3446 Black Creek Rd",
    address: {
      street: "3446 Black Creek Rd",
      city: "Fort Erie",
      state: "Ontario",
      zip: "L0S 1S0",
      country: "Canada"
    },
    price: "$649,900",
    beds: 4,
    baths: 2,
    sqft: 2278,
    lotSize: "30 x 120 ft",
    yearBuilt: 2010,
    propertyType: "Detached",
    status: "For Sale",
    description: "Lot Size  75x170-foot lot, there are alot of newer homes in the area with smaller lots, so this one stands out ",
    shortDescription: "4 BEDS + 2 BATHS",
    mainFeatures: [],
    heroImage: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1769200309659-MLS-2.jpg",
    heroCaption: "75x170 Lot + Huge Kitchen + Sunroom = Your Perfect Family Home Just Listed!",
    mapLocation: {
      lat: 43.6532,
      lng: -79.3832
    },
    virtualTourAvailable: false,
    virtualTourUrl: ""
  };

// propertyFeatures configuration
export const propertyFeatures = [
    {
      id: 1,
      title: "In a 2 story having a bedroom or office on the mainfloor, rather than all the bedrooms on the 2nd floor.",
      description: "In a 2 story having a bedroom or office on the mainfloor, rather than all the bedrooms on the 2nd floor.",
      icon: "CheckCircle"
    },
    {
      id: 2,
      title: "Lot Size  75x170-foot lot",
      description: "Lot Size  75x170-foot lot",
      icon: "CheckCircle"
    },
    {
      id: 3,
      title: "Size of the home - 4-bedroom, 2-bathroom home",
      description: "Size of the home - 4-bedroom, 2-bathroom home",
      icon: "CheckCircle"
    },
    {
      id: 4,
      title: "Large sunken living room at the back of the home",
      description: "Large sunken living room at the back of the home",
      icon: "CheckCircle"
    }
  ];

// siteBranding configuration
export const siteBranding = {
    logoUrl: "/logo.svg",
    colors: {
      primary: "#109fd9"
    },
    footer: {
      copyrightText: "© 2025 3446 Black Creek Rd. All rights reserved.",
      disclaimer: "This website is for informational purposes only. Details are subject to change.",
      privacyPolicyUrl: "https://expworldholdings.com/privacy-policy"
    },
    companyName: "Exp Realty",
    companyLogo: "/logo.svg",
    accentColor: "#109fd9",
    footerText: "© 2025 3446 Black Creek Rd. All rights reserved.",
    privacyPolicyUrl: "https://expworldholdings.com/privacy-policy"
  };

// siteMetadata configuration
export const siteMetadata = {
    title: "3446 Black Creek Rd | Detached | Fort Erie",
    description: "75x170 Lot + Huge Kitchen + Sunroom = Your Perfect Family Home Just Listed!",
    keywords: "detached, Fort Erie real estate, 4 bedroom, 2 bathroom, $649,900",
    ogImage: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1769200309659-MLS-2.jpg",
    ogType: "website",
    twitterCard: "summary_large_image",
    canonical: "https://3446blackcreekrd.com",
    twitterHandle: ""
  };

// testimonials configuration
export const testimonials = [
    {
      id: 1,
      name: "David Chen",
      role: "Recent Homebuyer",
      content: "Matt Goch provided exceptional service and found us exactly what we were looking for in Fort Erie.",
      avatar: "https://randomuser.me/api/portraits/men/22.jpg",
      rating: 5
    },
    {
      id: 2,
      name: "Jennifer Liu",
      role: "Interior Designer",
      content: "The attention to detail and quality of finishes in this property is outstanding. Matt Goch presented every detail clearly.",
      avatar: "https://randomuser.me/api/portraits/women/44.jpg",
      rating: 5
    },
    {
      id: 3,
      name: "Mark Williams",
      role: "Neighborhood Resident",
      content: "Living in this area, you appreciate the convenience and lifestyle. Matt Goch knows the market incredibly well.",
      avatar: "https://randomuser.me/api/portraits/men/35.jpg",
      rating: 5
    }
  ];

